### ISSUE TITLE
Axial attention

### ISSUE THREAD

**Issue by Jayden9912** [The-AI-Summer/self-attention-cv#15]
What is the meaning of qkv_channels?
https://github.com/The-AI-Summer/self-attention-cv/blob/5246e550ecb674f60df76a6c1011fde30ded7f44/self_attention_cv/axial_attention_deeplab/axial_attention.py#L32

**Comment by black0017** [comment]
Hi @Jayden9912 

This is because, as far as I can recall from my implementation, the dimensionality of V (Value representation) is different than the dimensionality of K and Q (keys and values). 

The projection is being done with a 1d , 1 by 1 conv instead of a nn.Linear layer. 

Does that answer your question?
